# -*- coding: utf-8 -*-
"""Student Attendance Management System

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iDjyX9aGZx4vad3tB5mGPkNxHJck0pyh
"""

students = []


def display_menu():
    print("\nStudent Attendance Management System")
    print("1. Add Student Attendance")
    print("2. View Attendance Records")
    print("3. Search Student")
    print("4. Calculate Attendance Percentage")
    print("5. Show Highest Attendance")
    print("6. Show Lowest Attendance")
    print("7. Count Total Students")
    print("8. Exit")


def add_attendance():
    name = input("Enter Student Name: ")
    student_id = input("Enter Student ID: ")
    classes_attended = int(input("Enter Classes Attended: "))
    total_classes = int(input("Enter Total Classes: "))

    student = [name, student_id, classes_attended, total_classes]
    students.append(student)

    print("\nAttendance record added successfully.")


def view_records():
    if len(students) == 0:
        print("No attendance records found.")
    else:
        for student in students:
            print("\nName:", student[0])
            print("ID:", student[1])
            print("Classes Attended:", student[2])
            print("Total Classes:", student[3])


def search_student():
    search_id = input("Enter Student ID to search: ")

    for student in students:
        if student[1] == search_id:
            print("\nName:", student[0])
            print("ID:", student[1])
            print("Classes Attended:", student[2])
            print("Total Classes:", student[3])
            return

    print("Student not found.")


def calculate_percentage(attended, total):
    if total == 0:
        return 0
    return (attended / total) * 100


def attendance_percentage():
    search_id = input("Enter Student ID: ")

    for student in students:
        if student[1] == search_id:
            percentage = calculate_percentage(student[2], student[3])
            print("Attendance Percentage:", round(percentage, 2), "%")
            return

    print("Student not found.")


def highest_attendance():
    if len(students) == 0:
        print("No records available.")
        return

    highest = students[0]
    highest_percentage = calculate_percentage(highest[2], highest[3])

    for student in students:
        percentage = calculate_percentage(student[2], student[3])

        if percentage > highest_percentage:
            highest = student
            highest_percentage = percentage

    print("\nHighest Attendance")
    print("Name:", highest[0])
    print("ID:", highest[1])
    print("Percentage:", round(highest_percentage, 2), "%")


def lowest_attendance():
    if len(students) == 0:
        print("No records available.")
        return

    lowest = students[0]
    lowest_percentage = calculate_percentage(lowest[2], lowest[3])

    for student in students:
        percentage = calculate_percentage(student[2], student[3])

        if percentage < lowest_percentage:
            lowest = student
            lowest_percentage = percentage

    print("\nLowest Attendance")
    print("Name:", lowest[0])
    print("ID:", lowest[1])
    print("Percentage:", round(lowest_percentage, 2), "%")


def count_students():
    print("\nTotal Students:", len(students))


while True:
    display_menu()

    choice = input("\nEnter your choice: ")

    if choice == "1":
        add_attendance()

    elif choice == "2":
        view_records()

    elif choice == "3":
        search_student()

    elif choice == "4":
        attendance_percentage()

    elif choice == "5":
        highest_attendance()

    elif choice == "6":
        lowest_attendance()

    elif choice == "7":
        count_students()

    elif choice == "8":
        print("\nProgram Ended.")
        break

    else:
        print("\nInvalid choice.")